spring:
  application:
    name: gift-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/LiuObstacle/gift-config.git
          username: LiuObstacle
          password: 3happy4ljz
          search-paths: src/main/resources # 如果不是在根路径下面需要加搜索地址

server:
  port: 10010
